# Generated by Django 5.2.7 on 2025-10-11 14:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('hours_used', models.FloatField(help_text='Total hours used this day')),
                ('kwh_used', models.FloatField(default=0.0)),
                ('co2_emission', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='ElectricDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('wattage', models.FloatField(help_text='Device power rating in watts')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ElectricityBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_date', models.DateField(help_text='Month or billing period date')),
                ('total_kwh', models.FloatField(default=0.0)),
                ('total_co2', models.FloatField(default=0.0)),
            ],
        ),
    ]
