# Generated by Django 5.2.7 on 2025-10-10 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_country_options_alter_district_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_co2_emission',
            field=models.FloatField(default=0.0),
        ),
    ]
