# Generated by Django 5.2.7 on 2025-10-11 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_total_co2_emission'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_from_electricity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='user',
            name='total_from_vehicles',
            field=models.FloatField(default=0.0),
        ),
    ]
