# Generated by Django 5.2.7 on 2025-10-11 14:42

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('food_waste', 'Food Waste'), ('plastic_bottle', 'Plastic Bottle'), ('cooking_gas', 'Cooking (Gas)'), ('water_usage', 'Water Usage'), ('other', 'Other')], max_length=50)),
                ('unit', models.CharField(editable=False, max_length=50)),
                ('emission_factor', models.FloatField(editable=False)),
            ],
            options={
                'unique_together': {('name', 'category')},
            },
        ),
        migrations.CreateModel(
            name='ActivityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('quantity', models.FloatField(default=0.0)),
                ('co2_emission', models.FloatField(default=0.0)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='activities.activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'activity', 'date')},
            },
        ),
    ]
