# Generated by Django 5.2.5 on 2025-08-26 12:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle', models.CharField(choices=[('bus', 'Bus'), ('train', 'Train'), ('cng', 'CNG Auto'), ('rickshaw', 'Rickshaw'), ('motorcycle', 'Motorcycle'), ('pickup', 'Pickup Truck'), ('car', 'Car'), ('truck', 'Truck'), ('microbus', 'Microbus'), ('bicycle', 'Bicycle'), ('electric_scooter', 'Electric Scooter'), ('jeep', 'Jeep'), ('tempo', 'Tempo'), ('launch', 'Launch'), ('airplane', 'Airplane')], default='BICYCLE', max_length=100)),
                ('distance', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0, message="Distance Can't Be Negative")])),
                ('co2_emission', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
