# Generated by Django 5.2.7 on 2025-10-11 14:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(choices=[('car', 'Car'), ('bike', 'Bike'), ('bus', 'Bus'), ('truck', 'Truck'), ('others', 'Others')], max_length=20)),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('cng', 'CNG'), ('electric', 'Electric'), ('hybrid', 'Hybrid')], max_length=20)),
                ('mileage', models.FloatField(default=15.0, help_text='Km per liter or per kWh')),
                ('total_co2_emission', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
            },
        ),
        migrations.CreateModel(
            name='VehicleUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('distance_km', models.FloatField(help_text='Distance traveled (km)')),
                ('fuel_used', models.FloatField(default=0.0)),
                ('co2_emission', models.FloatField(default=0.0)),
            ],
        ),
    ]
