# Generated by Django 5.2.7 on 2025-10-11 10:46

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(choices=[('car', 'Car'), ('bike', 'Bike'), ('bus', 'Bus'), ('truck', 'Truck'), ('others', 'Others')], max_length=20)),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('cng', 'CNG'), ('electric', 'Electric'), ('hybrid', 'Hybrid')], max_length=20)),
                ('mileage', models.FloatField(default=15.0, help_text='Km per liter or per kWh')),
                ('total_co2_emission', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'unique_together': {('user', 'name', 'mileage')},
            },
        ),
        migrations.CreateModel(
            name='VehicleUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('distance_km', models.FloatField(help_text='Distance traveled (km)')),
                ('fuel_used', models.FloatField(default=0.0)),
                ('co2_emission', models.FloatField(default=0.0)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='transport.vehicle')),
            ],
            options={
                'unique_together': {('vehicle', 'date')},
            },
        ),
    ]
