# Generated by Django 5.2.7 on 2025-10-11 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transport', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehicleusage',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='transport.vehicle'),
        ),
        migrations.AlterUniqueTogether(
            name='vehicle',
            unique_together={('user', 'name', 'mileage')},
        ),
        migrations.AlterUniqueTogether(
            name='vehicleusage',
            unique_together={('vehicle', 'date')},
        ),
    ]
